/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cgs.mpagent.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Agent {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Agent\",\"namespace\":\"com.cgs.mpagent.proto\",\"types\":[{\"type\":\"record\",\"name\":\"Disk\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"total\",\"type\":\"double\"},{\"name\":\"used\",\"type\":\"double\"},{\"name\":\"Mounted\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Process\",\"fields\":[{\"name\":\"pid\",\"type\":\"int\"},{\"name\":\"memory\",\"type\":\"int\"},{\"name\":\"command\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"JavaProcess\",\"fields\":[{\"name\":\"pid\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"heapMemoryUsed\",\"type\":\"long\"},{\"name\":\"heapMemoryMax\",\"type\":\"long\"},{\"name\":\"nonheapMemoryUsed\",\"type\":\"long\"},{\"name\":\"nonheapMemoryMax\",\"type\":\"long\"},{\"name\":\"threadCount\",\"type\":\"int\"},{\"name\":\"daemonThreadCount\",\"type\":\"int\"},{\"name\":\"peakThreadCount\",\"type\":\"int\"}]}],\"messages\":{\"getSystemName\":{\"request\":[],\"response\":\"string\"},\"getCpuPct\":{\"request\":[],\"response\":\"int\"},\"getMemoryPct\":{\"request\":[],\"response\":\"int\"},\"getSwapPct\":{\"request\":[],\"response\":\"int\"},\"getDiskIO\":{\"request\":[],\"response\":\"long\"},\"getNetIO\":{\"request\":[],\"response\":\"long\"},\"getFreeMemory\":{\"request\":[],\"response\":\"long\"},\"getDisks\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"Disk\"}},\"getPrcState\":{\"request\":[{\"name\":\"startup\",\"type\":\"string\"}],\"response\":\"Process\"},\"getJavaState\":{\"request\":[{\"name\":\"startup\",\"type\":\"string\"}],\"response\":\"JavaProcess\"},\"startService\":{\"request\":[{\"name\":\"name\",\"type\":\"string\"}],\"response\":\"boolean\"},\"stopService\":{\"request\":[{\"name\":\"name\",\"type\":\"string\"}],\"response\":\"boolean\"}}}");
  java.lang.CharSequence getSystemName() throws org.apache.avro.AvroRemoteException;
  int getCpuPct() throws org.apache.avro.AvroRemoteException;
  int getMemoryPct() throws org.apache.avro.AvroRemoteException;
  int getSwapPct() throws org.apache.avro.AvroRemoteException;
  long getDiskIO() throws org.apache.avro.AvroRemoteException;
  long getNetIO() throws org.apache.avro.AvroRemoteException;
  long getFreeMemory() throws org.apache.avro.AvroRemoteException;
  java.util.List<com.cgs.mpagent.proto.Disk> getDisks() throws org.apache.avro.AvroRemoteException;
  com.cgs.mpagent.proto.Process getPrcState(java.lang.CharSequence startup) throws org.apache.avro.AvroRemoteException;
  com.cgs.mpagent.proto.JavaProcess getJavaState(java.lang.CharSequence startup) throws org.apache.avro.AvroRemoteException;
  boolean startService(java.lang.CharSequence name) throws org.apache.avro.AvroRemoteException;
  boolean stopService(java.lang.CharSequence name) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Agent {
    public static final org.apache.avro.Protocol PROTOCOL = com.cgs.mpagent.proto.Agent.PROTOCOL;
    void getSystemName(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void getCpuPct(org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void getMemoryPct(org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void getSwapPct(org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void getDiskIO(org.apache.avro.ipc.Callback<java.lang.Long> callback) throws java.io.IOException;
    void getNetIO(org.apache.avro.ipc.Callback<java.lang.Long> callback) throws java.io.IOException;
    void getFreeMemory(org.apache.avro.ipc.Callback<java.lang.Long> callback) throws java.io.IOException;
    void getDisks(org.apache.avro.ipc.Callback<java.util.List<com.cgs.mpagent.proto.Disk>> callback) throws java.io.IOException;
    void getPrcState(java.lang.CharSequence startup, org.apache.avro.ipc.Callback<com.cgs.mpagent.proto.Process> callback) throws java.io.IOException;
    void getJavaState(java.lang.CharSequence startup, org.apache.avro.ipc.Callback<com.cgs.mpagent.proto.JavaProcess> callback) throws java.io.IOException;
    void startService(java.lang.CharSequence name, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void stopService(java.lang.CharSequence name, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}